version: '3.8'

services:
  jnj-auth-backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NPM_REGISTRY=https://registry.npmjs.org/
    container_name: jnj-auth-backend
    restart: unless-stopped
    ports:
      - "${PORT:-4001}:${PORT:-4001}"
    env_file:
      - .env
    # 프로덕션 모드에서는 볼륨 마운트 없이 빌드된 이미지 사용
    # 개발 모드에서만 아래 볼륨을 활성화
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    dns:
      - 8.8.8.8
      - 8.8.4.4
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:${PORT:-4001}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - jnj-network

networks:
  jnj-network:
    driver: bridge 